### PR TITLE
added opencv target

### PR DESCRIPTION
**Pull request by Fran-FC**
Fixed colcon build error

### CODE REVIEW

**Comment by zang09** [comment]
I think it's depends on ROS version, so can you PR this changes to `humble` branch?

**Comment by Fran-FC** [comment]
Done, may I close this PR?

**Comment by Fran-FC** [comment]
I just realized I could edit this PR to merge with other branch, I created a new one... Sorry noob error :')

**Comment by zang09** [comment]
I merged with new one, so close this PR.

**Pull request closed without merging**
